name: ForcePack
main: com.convallyria.forcepack.spigot.ForcePackSpigot
author: SamB440
website: https://fortitude.islandearth.net
softdepend: [ViaVersion, ItemsAdder]
version: '${version}'
api-version: 1.13
folia-supported: true