name: Build and Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'SamB440'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Handles Gradle wrapper validation and basic caching

      - name: Build and Publish to Convallyria repository
        run: ./gradlew build publish
        env:
          MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            **/build/libs/
            */build/libs/